@echo off
echo Starting Text-to-Handwriting Premium...
echo Installing dependencies if missing...
call npm install --silent

echo Starting local development server...
start http://localhost:5000
npm run dev
